routes/web.php
<?php

use App\Http\Controllers\HeroController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('heroes', 'HeroController');

Route::resource('zeroes', 'ZeroController');

app/Hero.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hero extends Model
{
    protected $fillable = ['heroes_name', 'origin', 'alias', 'power_level', 'signature_move'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HeroController.php
<?php

namespace App\Http\Controllers;

use App\Hero;
use Illuminate\Http\Request;

class HeroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title'] = 'Heroes Creation';
        $data['heroes'] = Hero::all();
        return view('create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'heroes_name' => 'required',
            'origin' => 'required',
            'alias' => 'nullable|string',
            'power_level' => 'required|numeric',
            'signature_move' => 'required'
        ]);
        $hero = Hero::create($validated);        
        $hero->save();
        return redirect('/heroes/create')->with('success', 'Heroes successfully saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Hero  $hero
     * @return \Illuminate\Http\Response
     */
    public function show(Hero $hero)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Hero  $hero
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['title'] = 'Edit Heroes';
        $data['hero'] = Hero::find($id);
        $data['heroes'] = Hero::all();
        return view('edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Hero  $hero
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {        
        $validated = $request->validate([
            'heroes_name' => 'required',
            'origin' => 'required',
            'alias' => 'nullable|string',
            'power_level' => 'required|numeric',
            'signature_move' => 'required'
        ]);
        Hero::where('id', $id)->update($validated);        
        return redirect('/heroes/create')->with('success', 'Heroes successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Hero  $hero
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hero = Hero::findOrFail($id);
        $hero->delete();

        return redirect('/heroes/create')->with('success', 'Heroes successfully deleted');
    }
}

app/Http/Controllers/ZeroController.php
<?php

namespace App\Http\Controllers;

use App\Hero;
use Illuminate\Http\Request;

class ZeroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title'] = 'Ajax Input test';
        return view('zero_create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/create.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-lg-3">

            @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
            @endif        

            <div class="card">
                <div class="card-header">
                    Heroes
                </div>
                <div class="card-body">
                    <form action="{{ route('heroes.store') }}" method="POST">

                        @csrf
                        <div class="form-group mb-2">
                            <label>Name</label>
                            <input type="text" name="heroes_name" class="form-control @error('heroes_name') is-invalid @enderror" value="{{ old('heroes_name') }}" placeholder="Heroes Name">
                            @error('heroes_name') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group mb-2">                            
                            <input type="text" name="origin" class="form-control @error('origin') is-invalid @enderror" value="{{ old('origin') }}" placeholder="Heroes Origin">
                            @error('origin') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group mb-2">                            
                            <input type="text" name="alias" class="form-control @error('alias') is-invalid @enderror" value="{{ old('alias') }}" placeholder="Alias">
                            @error('alias') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group">
                            <input type="number" name="power_level" class="form-control @error('power_level') is-invalid @enderror" value="{{ old('power_level') }}" placeholder="Power Level">
                            @error('power_level') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group">
                            <label>Signature</label>
                            <textarea name="signature_move" rows="3" class="form-control @error('signature_move') is-invalid @enderror" value="{{ old('signature_move') }}" placeholder="Signature Move"></textarea>
                            @error('signature_move') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>

                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>

        @include('layouts.table')

    </div>
</div>

@endsection

resources/views/edit.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-lg-3">

            @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
            @endif        

            <div class="card">
                <div class="card-header">
                    Heroes                    
                </div>
                <div class="card-body">
                    <form action="{{ route('heroes.update', $hero->id) }}" method="POST">

                        @csrf
                        @method('PATCH')

                        <div class="form-group mb-2">
                            <label>Name</label>
                            <input type="text" name="heroes_name" class="form-control @error('heroes_name') is-invalid @enderror" value="{{ $hero->heroes_name }}" placeholder="Heroes Name">
                            @error('heroes_name') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group mb-2">                            
                            <input type="text" name="origin" class="form-control @error('origin') is-invalid @enderror" value="{{ $hero->origin }}" placeholder="Heroes Origin">
                            @error('origin') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group mb-2">                            
                            <input type="text" name="alias" class="form-control @error('alias') is-invalid @enderror" value="{{ $hero->alias }}" placeholder="Alias">
                            @error('alias') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group">
                            <input type="number" name="power_level" class="form-control @error('power_level') is-invalid @enderror" value="{{ $hero->power_level }}" placeholder="Power Level">
                            @error('power_level') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group">
                            <label>Signature</label>
                            <textarea name="signature_move" rows="3" class="form-control @error('signature_move') is-invalid @enderror" placeholder="Signature Move">{{ $hero->signature_move }}</textarea>
                            @error('signature_move') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>

                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>

        @include('layouts.table')

    </div>
</div>

@endsection

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    @yield('meta_csrf')    

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    @yield('css')

    <title>@if($title) {{ $title }} @else Heroes @endif</title>

  </head>

  <body>

    @yield('content')

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    @yield('js')

  </body>
</html>

resources/views/layouts/table.blade.php
<div class="col-lg-9">
    <div class="card">
        <div class="card-header">
            Heroes List    
        </div>
        <div class="card-body">
            <div class="table">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Origin</th>
                            <th>Alias</th>
                            <th>Level</th>
                            <th>Signature Move</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($heroes as $hero)
                        <tr>
                            <td>{{ $hero->id }}</td>
                            <td>{{ $hero->heroes_name }}</td>
                            <td>{{ $hero->origin }}</td>
                            <td>{{ $hero->alias }}</td>
                            <td>{{ $hero->power_level }}</td>
                            <td>{{ $hero->signature_move }}</td>
                            <td>
                                <a href="{{ route('heroes.edit', $hero->id) }}" class="btn btn-primary">Edit</a>
                                <form action="{{ route('heroes.destroy', $hero->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

resources/views/zero_create.blade.php
@extends('layouts.master')

@section('meta_csrf')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-3">

            @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
            @endif

            <div class="card">
                <div class="card-header">
                    Heroes
                </div>
                <div class="card-body">
                    <form action="{{ route('zeroes.store') }}" method="POST">

                        <div class="form-group mb-2">
                            <label>Name</label>
                            <input type="text" name="heroes_name" class="form-control @error('heroes_name') is-invalid @enderror" value="{{ old('heroes_name') }}" placeholder="Heroes Name" v-model="heroesName">
                            @error('heroes_name') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group mb-2">
                            <input type="text" name="origin" class="form-control @error('origin') is-invalid @enderror" value="{{ old('origin') }}" placeholder="Heroes Origin" v-model="origin">
                            @error('origin') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group mb-2">
                            <input type="text" name="alias" class="form-control @error('alias') is-invalid @enderror" value="{{ old('alias') }}" placeholder="Alias" v-model="alias">
                            @error('alias') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group">
                            <input type="number" name="power_level" class="form-control @error('power_level') is-invalid @enderror" value="{{ old('power_level') }}" placeholder="Power Level" v-model="powerLevel">
                            @error('power_level') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>
                        <div class="form-group">
                            <label>Signature</label>
                            <textarea name="signature_move" rows="3" class="form-control @error('signature_move') is-invalid @enderror" value="{{ old('signature_move') }}" placeholder="Signature Move" v-model="signatureMove"></textarea>
                            @error('signature_move') <div class="text-danger mb-2"><small>{{ $message }}</small></div> @enderror
                        </div>

                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>

        <!--
            This will be vuetable
        -->

    </div>
</div>
@endsection

@section('js')
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<script>
    var vm = new Vue({
        el: '#app',
        data: {
            heroesName: '',
            origin: '',
            alias: '',
            powerLevel: '',
            signatureMove: ''
        },
        methods: {
            processForm() {

                var form = $('#form')
                var formData = new FormData(form[0])
                axios({
                        method: 'post',
                        url: "{{ site_url('leads/save') }}",
                        data: formData
                    })
                    .then(function(resp) {
                        console.log(resp)                        
                        vm.clearForm()
                    })
                    .catch(function(resp) {
                        console.log(resp)
                    })

            },
        }
    })
</script>

@endsection